### ISSUE TITLE
tergmprepare - consider check for userdefined ergm.userterms term names

### ISSUE THREAD

**Issue by marioangst** [leifeld/btergm#15] opened 2019-08-14 14:42 UTC
Small issue but it just got me into a bit of trouble. When working with terms created with ergm.userterm, functions such as edgecov will fail if custom term names coincidentally have similar names to existing terms in ergm. In my case this was because tergmprepare checks for some existing terms through regex matches (eg. in my case I created a term called twopathedgecov, which produces a match on line 77 of tergmprepare).

I guess a exact regex match might solve this?

All the best ;)

Mario

**Comment by leifeld** [comment] 2020-04-05 19:01
It may be a bit late for this, but if you can provide a minimal self-contained example, I can look into this. Thanks.

**Comment by leifeld** [comment] 2022-04-01 15:44
Closing because not reproducible/testable without example.

**Closed as completed by leifeld** 2022-04-01 15:44 UTC
